import { SongProvider } from "../context/SongProvider";
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SongProvider>
          { children }
        </SongProvider>
      </body>
    </html>
  )
}
